language: r
sudo: false
cache: packages

r:
  - release


before_install:
  - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
  - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
  - Rscript -e 'remotes::install_github(c("delta-rho/trelliscope","EMSL-Computing/MetaCycData"))'
